/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_arvalon_chapter9_JCPUStat */

#ifndef _Included_ru_arvalon_chapter9_JCPUStat
#define _Included_ru_arvalon_chapter9_JCPUStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_arvalon_chapter9_JCPUStat
 * Method:    getRSSMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_arvalon_chapter9_JCPUStat_getRSSMemory
  (JNIEnv *, jobject);

/*
 * Class:     ru_arvalon_chapter9_JCPUStat
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_arvalon_chapter9_JCPUStat_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
